# Generated by Django 4.0.6 on 2024-04-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_client_alter_modelo_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('dni', models.CharField(max_length=50, verbose_name='dni')),
                ('date_creation', models.DateField()),
                ('date_update', models.DateField()),
                ('satate', models.BooleanField(default=True)),
                ('idcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_client')),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
    ]
