# Generated by Django 4.0.6 on 2024-04-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('state', models.BooleanField(default=True)),
                ('idsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'verbose_name_plural': 'Venta',
            },
        ),
    ]
